<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note[
<!ELEMENT note (sms|email|mensajeria|to+,from,heading?,body)>
<!ELEMENT envio (SMS|mensajeria)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>
]>
<note>
<envio>sms</envio>
<to>Mercedez</to>
<from>Jose</from>
<heading>Recordar</heading>
<body>Nos olvides el cumpleaños de Andres</body>
</note>