<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda[
<!ELEMENT agenda (persona+)>
<!ELEMENT persona (nombre,tlf,tw)>
<!ATTLIST persona id ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tlf (#PCDATA)>
<!ELEMENT tw (#PCDATA)>
]>

<agenda>
<persona  id="rica">
<nombre>Ricardo Borriquero</nombre>
<tlf>951345679</tlf>
<tw>@ricardo</tw>
</persona>

<persona id="eva">
<nombre>Eva Risto</nombre>
<tlf>952342123</tlf>
<tw>@evaristo</tw>
</persona>
</agenda>